apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudscribe-api
  namespace: cloudscribe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudscribe-api
  template:
    metadata:
      labels:
        app: cloudscribe-api
    spec:
      containers:
        - name: api
          image: ghcr.io/thechaoticengineer/cloudscribe-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgres-service;Database=cloudscribe;Username=postgres;Password=$(POSTGRES_PASSWORD)"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudscribe-secrets
                  key: postgres-password
            
            - name: Authentication__Authority
              value: "http://keycloak-service:8080/realms/cloudscribe"
            - name: Authentication__MetadataAddress
              value: "http://keycloak-service:8080/realms/cloudscribe/.well-known/openid-configuration"
            - name: Authentication__RequireHttpsMetadata
              value: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: cloudscribe-api-service 
  namespace: cloudscribe
spec:
  ports:
    - port: 80       
      targetPort: 8080 
  selector:
    app: cloudscribe-api
  type: ClusterIP